# site settings
title: Eric
subtitle: Chiyembekeza
email: eric@qualichealth.com
description: Follow My journey with Data Science-<br /> projects, passions, and some problems mixed in.
baseurl: "/echiyembekeza.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
#street_address: 1234 Somewhere Road
city: W. Palm Beach
state: FL
zip_code: 33413
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
github_url:https://github.com/echiyembekeza
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/qualichealth
linkedin_url: https://www.linkedin.com/in/ericchiyembekeza
website_url: https://www.qualichealth.com
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
